pipeline {
    agent {
        label 'ecs-agent'
    }
    stages {
        stage('Build') { 
            agent {
                ecs {
                   inheritFrom 'ecs-agent'
                   image 'imranhomedocker/myjenkins-inbound:latest'
                }
            }
            steps {
                sh 'mvn -B -DskipTests clean package' 
            }
        }
    }
}
