pipeline {
        agent {
            ecs {
                inheritFrom 'ecs-agent-firefox'
                image 'imranhomedocker/myjenkins-inbound:latest'
            }
        }
    stages {
        stage('Build') { 
            steps {
                sh """
                    mvn -B -DskipTests clean package'
            
                    java -jar ./target/GuiTester.jar scripts/nofrills_flyer.txt
                """
            }
        }
    }
}
