pipeline {
        agent {
            ecs {
                label 'ecs-agent-firefox'
            }
        }
    stages {
        stage('Build') { 
            steps {
                sh """
                    mvn -B -DskipTests clean package
            
                    java -jar ./target/GuiTester.jar scripts/nofrills_flyer.txt
                """
            }
        }
    }
}
